### ISSUE TITLE
Add another file

### ISSUE THREAD

**Issue by athatheo** [Ariwor/cpp-shenanigans#3]
Create a second file that connects somehow to the first file. Maybe uses  a function? Or create a child class? Avoid using all th elines of code in the main functions as this prevents modularity.

**Comment by Ariwor** [comment]
This is the plan, wait for it. I was just doing some toy examples from a lecture and functions are in the next one :P

**Comment by athatheo** [comment]
Cool, let me know when you have the patch ready since it breaks some builds I got; also I don't like leaving security issues open. Props for the great job so far tho!

**Comment by Ariwor** [comment]
@athatheo added (4d145cdd57204499a7ae685cbafb5f51ae2cf613) a very simple function for your team to use (& the associated header file). It is able to estimate the square root of an input number. These are exciting times for the company for sure!

**Comment by athatheo** [comment]
Wow. I'll be clsoing this. Thank you for this; exciting times indeed.
