### ISSUE TITLE
Consider using std::endl instead of \n

### ISSUE THREAD

**Issue by kongr45gpen** [Ariwor/cpp-shenanigans#5]
Check https://stackoverflow.com/questions/213907/stdendl-vs-n for a discussion on the matter.

In short:

1. `std::endl` makes your code more readable. What is this `\n` stuff? Who knows
2. `std::endl` will automatically be converted to `\r\n` (instead of `\n`) when saving files on other platforms like Windows
3. `std::endl` automatically flushes the output, so maybe you will see your messages faster, who knows. However, in case you're going for that programming contest, this may introduce performance issues.

**Comment by athatheo** [comment]
Wow, interesting take indeed. Using just endl since the std namespace is included is the way to go.

**Comment by Ariwor** [comment]
Sure, this is the way, included it in an example as well.
