### ISSUE TITLE
More resources

### ISSUE THREAD

**Issue by kongr45gpen** [Ariwor/cpp-shenanigans#7]
Here's a list of more resources that you should consider looking at - they have been very helpful for me:

- [cppreference.com](https://en.cppreference.com/w/), which is a very easily browser of EVERY feature in a language. Go-to reference for any function or feature I want to look up.
- [ISO C++ Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) with a lot of best practices and background information from the C++ committee
  - [There is also this tour of modern C++](https://isocpp.org/tour)
- [C++ notes for professionals](https://goalkicker.com/CPlusPlusBook/): This is actually a collection of stack-overflow answers to popular questions - nothing more!
- [Programming: Principles and Practice Using C++](https://www.amazon.com/dp/0321992784) which is a great, strong and long introductory book about C++ by Stroustroup, with a lot of commentary, details and thoughts.

**Comment by Ariwor** [comment]
Thanks, will look into them! Already added them in the resources in the `README`.

**Comment by xlxs4** [comment]
@Ariwor I think you are ready to tackle on more advanced stuff.. for a light watch I'd recommend something like https://www.youtube.com/user/lefticus1
